<a href="https://colab.research.google.com/github/TechWhizGenius/Teja_INFO5731_Fall2024/blob/main/Mandaloju_Teja_Exercise_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 In-class Exercise 3**

The purpose of this exercise is to explore various aspects of text analysis, including feature extraction, feature selection, and text similarity ranking.

**Expectations**:
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

**Total points**: 40

**Deadline**: This in-class exercise is due at the end of Friday, at 11:59 PM.

**Late submissions will have a penalty of 10% of the marks for each day of late submission. , and no requests will be answered. Manage your time accordingly.**

**Please check that the link you submitted can be opened and points to the correct assignment.**

## Question 1 (10 Points)
Describe an interesting **text classification or text mining task** and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features. **Your dataset must be text.**

In [41]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''

Task: Genre Classification of Books

Description:

I want to build a machine learning model that can classify books into their respective genres (e.g., Fiction, Non-Fiction, Science Fiction, Mystery,
 Romance) based on the titles and descriptions. This classification could help readers find books they might enjoy and assist publishers in
 organizing their catalogs.

Useful Features for the Machine Learning Model:

1.Bag of Words (BoW):This feature represents the text data as a collection of individual words, ignoring the order but keeping track of the frequency
of each word. BoW helps in capturing the most common words in titles and descriptions that can indicate the genre. For example, the presence of
words like "mystery," "detective," or "romance" could be strong indicators of their respective genres.

2.TF-IDF (Term Frequency-Inverse Document Frequency): TF-IDF weighs the frequency of a word in a document relative to its frequency across all
documents. This helps to reduce the importance of common words (like "the," "is") and emphasize words that are more unique to specific genres.By
focusing on words that are more characteristic of particular genres, TF-IDF can improve the model's ability to distinguish between different genres
 effectively.

3.N-grams: N-grams capture sequences of 'n' words in the text. For example, bigrams (2-grams) will look at pairs of consecutive words.Some genres
might have specific phrases that are common within them (e.g., "science fiction" or "love story"). By capturing these sequences, we can provide
additional context that might help the model make better predictions.

4.Part-of-Speech (POS) Tags: POS tagging involves identifying the grammatical parts of speech (like nouns, verbs, adjectives) in the text.The style
 and structure of the title and description can give insights into the genre. For example, a book with many adjectives may suggest a descriptive or
  romantic genre, while a book heavy in nouns may indicate a more factual or technical genre.

5.Word Length and Title Length:This feature measures the average length of words and the overall length of the book titles and descriptions.Certain
 genres might be characterized by longer, more complex titles or descriptions. For instance, fantasy novels often have longer, more descriptive
 titles, while thrillers might have shorter, punchier titles.

6.Sentiment Analysis Scores:This involves calculating sentiment scores (positive, negative, neutral) for the text data using a sentiment analysis
 tool or lexicon.Different genres can evoke different sentiments. For example, romance novels might have a more positive sentiment compared to
 horror novels, which might lean towards negative. This feature can provide an additional layer of understanding about the content of the book.


By utilizing a combination of these features, we can construct a robust machine learning model capable of classifying books into their respective
genres based on their titles and descriptions. Each feature provides different insights into the text, enabling the model to learn patterns that
differentiate genres effectively.


'''

' \n\nTask: Genre Classification of Books\n\nDescription:  \n\nI want to build a machine learning model that can classify books into their respective genres (e.g., Fiction, Non-Fiction, Science Fiction, Mystery,\n Romance) based on the titles and descriptions. This classification could help readers find books they might enjoy and assist publishers in \n organizing their catalogs.\n\nUseful Features for the Machine Learning Model:\n\n1.Bag of Words (BoW):This feature represents the text data as a collection of individual words, ignoring the order but keeping track of the frequency\nof each word. BoW helps in capturing the most common words in titles and descriptions that can indicate the genre. For example, the presence of \nwords like "mystery," "detective," or "romance" could be strong indicators of their respective genres.\n\n2.TF-IDF (Term Frequency-Inverse Document Frequency): TF-IDF weighs the frequency of a word in a document relative to its frequency across all \ndocuments. This

## Question 2 (10 Points)
Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [42]:
import requests
from bs4 import BeautifulSoup
import time

# Base URL
base_url = "http://books.toscrape.com/"

#Fetch the main page and get individual book URLs
response = requests.get(base_url)

if response.status_code == 200:
    print("Successfully fetched the webpage!")
else:
    print(f"Failed to fetch the webpage. Status code: {response.status_code}")

# Parse the main page
soup = BeautifulSoup(response.content, 'html.parser')

# Initialize lists to store titles and descriptions
book_titles = []
book_descriptions = []

# Find all book titles and links to individual book pages
books = soup.find_all('article', class_='product_pod')

# Visit individual book pages to extract titles and descriptions
for i, book in enumerate(books[:10], 1):  # Limit to 10 books
    title = book.h3.a['title']
    book_url = base_url + book.h3.a['href']
    book_titles.append(title)

    # Fetch individual book page to get the description
    book_response = requests.get(book_url)
    book_soup = BeautifulSoup(book_response.content, 'html.parser')

    # Extract the description from the book page
    description = book_soup.find('meta', attrs={"name": "description"})['content'].strip()

    book_descriptions.append(description)

    # Optional delay to avoid hitting the server too quickly
    time.sleep(1)

print(book_titles)
print(book_descriptions)

Successfully fetched the webpage!
['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind', 'The Requiem Red', 'The Dirty Little Secrets of Getting Your Dream Job', 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'The Black Maria']
["It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special editio

In [43]:
# 1.Bag of Words (BoW)

from sklearn.feature_extraction.text import CountVectorizer

def extract_bow(titles, descriptions):
    vectorizer_bow = CountVectorizer()
    combined_text = [f"{title} {description}" for title, description in zip(titles, descriptions)]
    X_bow = vectorizer_bow.fit_transform(combined_text)
    return vectorizer_bow.get_feature_names_out(), X_bow.toarray()

# Extract BoW features
bow_features, bow_matrix = extract_bow(book_titles, book_descriptions)

# Print entire results of Bag of Words
print("Bag of Words Features:")
print(bow_features)

print("\nBoW Matrix:")
for i in range(bow_matrix.shape[0]):
    print(f"Book {i + 1}: {bow_matrix[i]}")


Bag of Words Features:
['000' '140' '14th' ... 'young' 'your' 'yuval']

BoW Matrix:
Book 1: [0 0 0 ... 0 1 0]
Book 2: [0 0 0 ... 0 0 0]
Book 3: [0 0 0 ... 0 0 0]
Book 4: [0 0 0 ... 1 0 0]
Book 5: [1 0 0 ... 0 0 1]
Book 6: [0 0 0 ... 0 0 0]
Book 7: [0 0 0 ... 0 5 0]
Book 8: [0 2 1 ... 0 0 0]
Book 9: [0 0 0 ... 0 0 0]
Book 10: [0 0 0 ... 0 3 0]


In [44]:
# 2.TF-IDF (Term Frequency-Inverse Document Frequency)

from sklearn.feature_extraction.text import TfidfVectorizer

def extract_tfidf(titles, descriptions):
    vectorizer_tfidf = TfidfVectorizer()
    combined_text = [f"{title} {description}" for title, description in zip(titles, descriptions)]
    X_tfidf = vectorizer_tfidf.fit_transform(combined_text)
    return vectorizer_tfidf.get_feature_names_out(), X_tfidf.toarray()

# Extract TF-IDF features
tfidf_features, tfidf_matrix = extract_tfidf(book_titles, book_descriptions)

print("TF-IDF Features:")
print(tfidf_features)
print("TF-IDF Matrix:")
print(tfidf_matrix)
print()


TF-IDF Features:
['000' '140' '14th' ... 'young' 'your' 'yuval']
TF-IDF Matrix:
[[0.         0.         0.         ... 0.         0.04432477 0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.05124306 0.02562153 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.07460843 0.        ]]



In [45]:
# 3.N-grams: (Bigrams)

def extract_ngrams(titles, descriptions):
    vectorizer_ngrams = CountVectorizer(ngram_range=(2, 2))  # Bigrams
    combined_text = [f"{title} {description}" for title, description in zip(titles, descriptions)]
    X_ngrams = vectorizer_ngrams.fit_transform(combined_text)
    return vectorizer_ngrams.get_feature_names_out(), X_ngrams.toarray()

# Extract N-grams features
ngram_features, ngram_matrix = extract_ngrams(book_titles, book_descriptions)

print("N-grams (Bigrams) Features:")
print(ngram_features)
print("N-grams Matrix:")
print(ngram_matrix)
print()


N-grams (Bigrams) Features:
['000 years' '140 years' '14th and' ... 'your indifferenceyour'
 'your rage' 'yuval noah']
N-grams Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 2 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]]



In [46]:
# 4.Part-of-Speech (POS) Tags

import nltk

nltk.download('punkt')

def extract_pos_tags(titles, descriptions):
    pos_tags = []
    for title, description in zip(titles, descriptions):
        text = f"{title} {description}"
        tokens = nltk.word_tokenize(text)
        tags = nltk.pos_tag(tokens)  # (word, POS tag)
        pos_tags.append(tags)
    return pos_tags

# Extract POS tags
pos_tags = extract_pos_tags(book_titles, book_descriptions)

print("POS Tags:")
for i, tags in enumerate(pos_tags):
    print(f"Book {i+1}: {tags}")
print()


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


POS Tags:
Book 1: [('A', 'DT'), ('Light', 'NNP'), ('in', 'IN'), ('the', 'DT'), ('Attic', 'NNP'), ('It', 'PRP'), ("'s", 'VBZ'), ('hard', 'JJ'), ('to', 'TO'), ('imagine', 'VB'), ('a', 'DT'), ('world', 'NN'), ('without', 'IN'), ('A', 'DT'), ('Light', 'NNP'), ('in', 'IN'), ('the', 'DT'), ('Attic', 'NNP'), ('.', '.'), ('This', 'DT'), ('now-classic', 'JJ'), ('collection', 'NN'), ('of', 'IN'), ('poetry', 'NN'), ('and', 'CC'), ('drawings', 'NNS'), ('from', 'IN'), ('Shel', 'NNP'), ('Silverstein', 'NNP'), ('celebrates', 'VBZ'), ('its', 'PRP$'), ('20th', 'JJ'), ('anniversary', 'NN'), ('with', 'IN'), ('this', 'DT'), ('special', 'JJ'), ('edition', 'NN'), ('.', '.'), ('Silverstein', 'NNP'), ("'s", 'POS'), ('humorous', 'JJ'), ('and', 'CC'), ('creative', 'JJ'), ('verse', 'NN'), ('can', 'MD'), ('amuse', 'VB'), ('the', 'DT'), ('dowdiest', 'JJS'), ('of', 'IN'), ('readers', 'NNS'), ('.', '.'), ('Lemon-faced', 'JJ'), ('adults', 'NNS'), ('and', 'CC'), ('fidgety', 'NN'), ('kids', 'NNS'), ('sit', 'NN'), ('sti

In [47]:
# 5. Feature Extraction: Word Length and Title Length

def extract_length_features(titles, descriptions):
    lengths = []
    for title, description in zip(titles, descriptions):
        title_length = len(title.split())
        description_length = len(description.split())
        lengths.append((title_length, description_length))
    return lengths

# Extract Length features
length_features = extract_length_features(book_titles, book_descriptions)

print("Word Length and Title Length (Title Length, Description Length):")
for i, lengths in enumerate(length_features):
    print(f"Book {i+1}: Title Length = {lengths[0]}, Description Length = {lengths[1]}")
print()


Word Length and Title Length (Title Length, Description Length):
Book 1: Title Length = 5, Description Length = 164
Book 2: Title Length = 3, Description Length = 165
Book 3: Title Length = 1, Description Length = 163
Book 4: Title Length = 2, Description Length = 274
Book 5: Title Length = 6, Description Length = 304
Book 6: Title Length = 3, Description Length = 170
Book 7: Title Length = 9, Description Length = 284
Book 8: Title Length = 15, Description Length = 568
Book 9: Title Length = 18, Description Length = 335
Book 10: Title Length = 3, Description Length = 464



In [48]:
# 6. Feature Extraction: Sentiment Analysis Scores

from textblob import TextBlob


def extract_sentiment(titles, descriptions):
    sentiments = []
    for title, description in zip(titles, descriptions):
        text = f"{title} {description}"
        blob = TextBlob(text)
        sentiments.append((blob.sentiment.polarity, blob.sentiment.subjectivity))  # polarity, subjectivity
    return sentiments

# Extract Sentiment scores
sentiment_scores = extract_sentiment(book_titles, book_descriptions)

print("Sentiment Analysis Scores (Polarity, Subjectivity):")
for i, scores in enumerate(sentiment_scores):
    print(f"Book {i+1}: Polarity = {scores[0]:.2f}, Subjectivity = {scores[1]:.2f}")
print()


Sentiment Analysis Scores (Polarity, Subjectivity):
Book 1: Polarity = 0.26, Subjectivity = 0.51
Book 2: Polarity = 0.12, Subjectivity = 0.50
Book 3: Polarity = 0.00, Subjectivity = 0.00
Book 4: Polarity = -0.03, Subjectivity = 0.49
Book 5: Polarity = 0.00, Subjectivity = 0.37
Book 6: Polarity = 0.03, Subjectivity = 0.45
Book 7: Polarity = 0.01, Subjectivity = 0.57
Book 8: Polarity = 0.24, Subjectivity = 0.53
Book 9: Polarity = 0.11, Subjectivity = 0.46
Book 10: Polarity = 0.17, Subjectivity = 0.47



## Question 3 (10 points):
Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [49]:
# I would like to use Filter Methods - Chi-Squared Test to evaluate the importance of features.

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_selection import chi2
from sklearn.datasets import make_multilabel_classification

# creating some binary labels (0 or 1) for classification purposes.
labels = np.random.randint(0, 2, size=(len(book_titles), 1))

# Combine titles and descriptions for feature extraction
combined_text = [f"{title} {description}" for title, description in zip(book_titles, book_descriptions)]

# Extract features using Bag of Words
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(combined_text)

# Apply Chi-Squared Test
chi2_scores, p_values = chi2(X, labels)

# Create a DataFrame for easy interpretation
feature_names = vectorizer.get_feature_names_out()
chi2_df = pd.DataFrame({
    'Feature': feature_names,
    'Chi2 Score': chi2_scores
})

# Rank features based on Chi-Squared scores in descending order
chi2_df = chi2_df.sort_values(by='Chi2 Score', ascending=False).reset_index(drop=True)

# Display the ranked features
print("Ranked Features based on Chi-Squared scores:")
print(chi2_df)


Ranked Features based on Chi-Squared scores:
        Feature  Chi2 Score
0           the   36.945055
1         woman   16.000000
2            of   15.043956
3           job   12.000000
4            in   11.520000
...         ...         ...
1150        may    0.000000
1151     poetry    0.000000
1152     begins    0.000000
1153       girl    0.000000
1154  beautiful    0.000000

[1155 rows x 2 columns]


## Question 4 (10 points):
Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [50]:
# You code here (Please add comments in the code):


import torch
from transformers import BertTokenizer, BertModel
from sklearn.metrics.pairwise import cosine_similarity


# Initialize the BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Function to encode text using BERT
def encode_texts(texts):
    inputs = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state.mean(dim=1)  # Use mean of all token embeddings

# Encode the book descriptions
book_embeddings = encode_texts(book_descriptions)

# Define a query
query = "a story about love and friendship"
query_embedding = encode_texts([query])

# Calculate cosine similarity between the query and book descriptions
similarity_scores = cosine_similarity(query_embedding.numpy(), book_embeddings.numpy())

# Rank the texts based on similarity scores
ranked_indices = similarity_scores[0].argsort()[::-1]  # Sort in descending order

# Print the ranked results
print("Ranking of books based on query similarity:")
for rank, index in enumerate(ranked_indices, start=1):
    print(f"Rank {rank}: {book_titles[index]} (Score: {similarity_scores[0][index]:.4f})")



/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


Ranking of books based on query similarity:
Rank 1: A Light in the Attic (Score: 0.6085)
Rank 2: The Requiem Red (Score: 0.6026)
Rank 3: Tipping the Velvet (Score: 0.6014)
Rank 4: The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics (Score: 0.5893)
Rank 5: The Black Maria (Score: 0.5784)
Rank 6: Sapiens: A Brief History of Humankind (Score: 0.5600)
Rank 7: Sharp Objects (Score: 0.5577)
Rank 8: The Dirty Little Secrets of Getting Your Dream Job (Score: 0.5420)
Rank 9: The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull (Score: 0.5128)
Rank 10: Soumission (Score: 0.3777)


# Mandatory Question

**Important: Reflective Feedback on this exercise**

Please provide your thoughts and feedback on the exercises you completed in this assignment. Consider the following points in your response:

Learning Experience: Describe your overall learning experience in working on extracting features from text data. What were the key concepts or techniques you found most beneficial in understanding the process?

Challenges Encountered: Were there specific difficulties in completing this exercise?

Relevance to Your Field of Study: How does this exercise relate to the field of NLP?

**(Your submission will not be graded if this question is left unanswered)**



In [51]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''

Working on extracting features from text data was a highly enriching experience. One of the key concepts I found beneficial was the understanding
of various feature extraction methods, such as Bag of Words (BoW) and advanced techniques like BERT embeddings. Learning how to represent text in
a numerical format is crucial for building machine learning models. Additionally, exploring feature selection methods highlighted the importance
of identifying the most informative features to improve model performance and interpretability. The hands-on experience with libraries like
scikit-learn and transformers made the concepts more tangible and applicable.

As I am new to NLP and preprocessing tasks, I found understanding and implementing it for a real world scenario is challenging. Particularyly,
I found the initial web scraping to be challenging.And Finally, I would say this exercise is highly relevant to the field of NLP, as feature
extraction and selection are foundational steps in building effective text classification models.

'''

'\n\nWorking on extracting features from text data was a highly enriching experience. One of the key concepts I found beneficial was the understanding \nof various feature extraction methods, such as Bag of Words (BoW) and advanced techniques like BERT embeddings. Learning how to represent text in \na numerical format is crucial for building machine learning models. Additionally, exploring feature selection methods highlighted the importance\nof identifying the most informative features to improve model performance and interpretability. The hands-on experience with libraries like \nscikit-learn and transformers made the concepts more tangible and applicable.\n\nAs I am new to NLP and preprocessing tasks, I found understanding and implementing it for a real world scenario is challenging. Particularyly,\nI found the initial web scraping to be challenging.And Finally, I would say this exercise is highly relevant to the field of NLP, as feature\nextraction and selection are foundational st